### ISSUE TITLE
[next] Maybe handling

### ISSUE THREAD

**Issue by mathiask88** [nodejs/nan#367]
NanNew/NanTo/NanGet... respectively v8 will bring in many Maybe(Local) types. While  I understand the basics of a Maybe monad I don't really know how to handle all these. Do I really need to check every maybe if it is empty though I didn't check the commands before these changes? What's the best practise? Or was my code already wrong because I didn't  try catched everything?
Also I cant find anything in v8 docs why these functions may fail.

**Comment by kkoopa** [comment]
Scripts and regexes can fail due to bad input. Strings fail due to max length exceeded. Dates fail due to bad input. Buffers fsil due to memory allocation error. They all used to return empty handles in these cases, handles that needed checking. So yes, your old code was technically wrong. V8 now enforces this check on all results from functions that may fail. Think of it as an explicit contract for null checking.

**Comment by mathiask88** [comment]
Ok thanks and what about the To..Converters? If I checked e.g an argument with Is...() then I can safely do ToLocalChecked()? And why does the Object->Has() returns a Maybe<bool>, what can fail by checking if an Object has a property? Looks like maybes everywhere and writing addons will end up in a checking tangle.

**Comment by kkoopa** [comment]
Yes, if you are confident the check will pass, you can do a ToLocalChecked. Object->Has returns a
If the Maybe is nothing or the MaybeLocal is empty, it means that the API call either threw an exception or an exception was already pending. For Object->Has, I believe it can fail if you supply a null context.
Yes, that is how it will be.

**Comment by mathiask88** [comment]
Null context would probably a NAN error because the context is hidden, so Has should be safe. Ok thanks for your help. Maybe a small Maybe handling section in the docs would be great but maybe I am the only one having some issues with this ;)

**Comment by bnoordhuis** [comment]
> For Object->Has, I believe it can fail if you supply a null context.

`v8::Object::Has()` does a regular property lookup that consults accessors in the prototype chain.  That means it calls into JS code if for example the property is a JS getter.

If you don't want that, there's `v8::Object::HasRealNamedProperty()`.  It follows the prototype chain but won't call accessors.

It can still fail if there is an already pending exception, that's why it has a `Maybe<bool>` return value.
