### ISSUE TITLE
Nan::New<T> should almost always return MaybeLocal

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/nan#395]
Only a handful of `New<T>` overloads return `MaybeLocal<T>` at the moment.

In practice, everything that's not a singleton primitive (anything that's not true, false, undefined or null) can fail under OOM conditions.

If nothing else, the current MaybeLocal/Local dichotomy is kind of ad hoc and inconsistent.  For example, the overloads for `v8::Date` and `v8::RegExp` return a MaybeLocal, the ones for `v8::Array` and `v8::Object` return _das Ding an sich_, even though they're all heap objects.

**Comment by kkoopa** [comment]
That's the way it is in V8.

**Comment by bnoordhuis** [comment]
Okay, but I'll bet you a beer it's not going to stay that way.

**Comment by kkoopa** [comment]
Perhaps it won't stay, but there have been no concrete indications of an oncoming change yet. The code will adapt if it has to. I beg you not to inquire about the state of this from the V8 devs, lest you stir up a new set of changes.

**Comment by rvagg** [comment]
> I beg you not to inquire about the state of this from the V8 devs, lest you stir up a new set of changes.

you've made my day, nearly spat out my coffee while reading that

**Comment by saper** [comment]
I think that https://code.google.com/p/v8/issues/detail?id=3929 indicates, that `MaybeLocal<>` is da future. Whenever there is exception now, empty handle will be returned.

**Comment by kkoopa** [comment]
That issue is several months old. It seems resolved, since the last two commits are

https://chromium.googlesource.com/v8/v8.git/+/7f38011a04ca27e8f88b300713c8dc05ba8d61d7
convert last api functions which try to handle exceptions to maybes

and

https://chromium.googlesource.com/v8/v8.git/+/5d8e3bfaffd1c0edac4f03b41767b101dd75c482
Clarify what APIs return Maybe and MaybeLocal values
