### ISSUE TITLE
Nan::SetAccessor() doesn't handle v8::Handle<v8::Object> as first parameter

### ISSUE THREAD

**Issue by evantorrie** [nodejs/nan#467]
I'm migrating a nodejs v0.10/0.12 extension using `nan-1.x` to a v4.0.0 extension using `nan-2.0`.

The extension provides property getters/setters on the `exports` object itself.

### Nan-1.x

 I used to do this by declaring the getters and setters using `NAN_GETTER(FooGetter) { ... }` and then in the module init function, using

```cpp
void
init (Handle<Object> target) {
   target->SetAccessor(NanNew("foo"), FooGetter, 0);
  ...
}
```

### Nan-2.x

I tried to switch to using `Nan::SetAccessor`, e.g.

```cpp
NAN_MODULE_INIT(init) {
  Nan::SetAccessor(target, Nan::New("foo").ToLocalChecked(), FooGetter, 0);
}
```

While this works fine for nodejs-4.x, it fails under 0.12 and 0.10 because `Nan::SetAccessor()` is not able to take `ADDON_REGISTER_FUNCTION_ARGS_TYPE` as its first parameter, unlike, `Nan::Export()` for example.

Also, `NAN_GETTER(FooGetter)` now uses the internal nan-2.x PropertyCallback type, rather than the native v8 PropertyCallback, so it's non-obvious to me how to even fallback to using the native v8 SetAccessor function on the object handle via a `#if NODE_MODULE_VERSION < IOJS_3_0_MODULE_VERSION` style fallback to native v8 API.

Any suggestions?

**Comment by kkoopa** [comment]
```c++
#if NODE_MODULE_VERSION < IOJS_3_0_MODULE_VERSION
Local<Object> exports = Nan::New<Object>(target);
#else
Local<Object> exports = Nan::New<Object>(target);
#endif

Nan::SetAccessor(exports, Nan::New("foo").ToLocalChecked(), FooGetter, 0);
```

**Comment by evantorrie** [comment]
Works for me :+1:

**Comment by kkoopa** [comment]
Maybe I ought to restore some form of `Nan::EnsureLocal` to handle this in a slightly more convenient way.

**Comment by evantorrie** [comment]
That's fine by me for this (unusual?) case.

I do have a larger issue I'm trying to understand for someone coming from Nan-1.x (and perhaps this isn't the appropriate venue).

In 1.x, I was always under the assumption that we needed a `HandleScope` in any function where we had a `Local<Value>` style variable declaration.  And `EscapableHandleScope` wherever we returned one of those `Local<Value>` to the caller.

However, in Nan 2.x, the comment is that for `NAN_METHOD`, `NAN_GETTER` etc, there is an _implicit_ `HandleScope` created.  

Where is this done?  

Is this simply stating that because these functions are called from existing Javascript code, there must already be the appropriate type of `HandleScope` on the stack from earlier in the stack chain (i.e. within the Javascript code that called this function).

When is this false?  i.e. when would there not be a HandleScope created on the stack chain prior to our code being executed...  things like libuv callbacks?  Code that manipulates Javascript variables that isn't necessarily called from Javascript?

Perhaps some clarification in the documentation for people coming from 1.x would be good?

**Comment by kkoopa** [comment]
Yes, this case is slightly unusual. Normally, people call another init-like function from the init method and use Locals all the way from there on. Unfortunately, the deprecation of Handles created this annoying edge case which cannot be worked around in any truly wonderful way.

You seem to have inferred everything correctly. There was always an implicit scope created by Node (or was it V8) when calling from JavaScript to C++. With past versions of NAN scopes were always required due to the way things were set up with NanReturnValue mapping to scope.Close() with the assumption that there was a scope named scope. Since NAN 2, that limitation has been removed and it is no longer necessary to create a scope as far as NAN is concerned.

Scopes are required for libuv callbacks (and other functions not directly exposed to V8) when _creating_ _new_ handles to V8 objects. Having extra scopes is not wrong, it is simply unnecessary. While this can be considered as leaking implementation details, it's been the case for so long that it cannot reasonably be changed without breaking everything, and it won't be changed.
