### ISSUE TITLE
Support for Node 5+

### ISSUE THREAD

**Issue by AshleyScirra** [nodejs/nan#531]
The readme only advertises Node support up to 4. Node 5 is now used in NW.js 0.13.0-beta2, and this appears to be holding up support for other NW.js addons like greenworks: https://github.com/greenheartgames/greenworks/issues/64

**Comment by AshleyScirra** [comment]
Actually in the referenced issue it sounds like there is support already, but it's not advertised in the readme. I guess you just want to update the supported versions?

**Comment by kkoopa** [comment]
That line actually reflects what the latest version available was at time of publication, which is not necessarily the latest supported version. They often happen to coincide, but since no changes have been necessary for Node 5 support, and no features have been added to NAN lately, there has been no new version released in a couple of months. Node 5 is [tested and working](https://travis-ci.org/nodejs/nan).

Basically, if a new version of Node seems to work with the latest version of NAN, it works and is supported. If something breaks, a new version gets published as soon as possible to fix it. It seems unnecessary to publish a new version of NAN with nothing but a version bump every time there is a new release of Node.

As it happens, some minor updates have accumulated in NAN and a new minor release will be out soon and the documentation will be updated to reflect what the latest Node version is at the time of its release.
