### ISSUE TITLE
The second argument overrides value of the first one when get passed to native function for debug build only

### ISSUE THREAD

**Issue by IdeaHunter** [nodejs/nan#532]
Faced really neat issue with function arguments passed to native addon.
When the function below got called from js code it return value of the *second* argument instead of the first one:

```c++
NAN_METHOD(Method) {
  const char* first = *Nan::Utf8String(info[0]);
  const char* second __attribute__((unused)) = *Nan::Utf8String(info[1]);

  info.GetReturnValue().Set(Nan::New(first).ToLocalChecked());
}
```

The issue can be reproduced **only** for --debug build, without --debug it works pretty fine.
I created a repo [IdeaHunter/node-addon-testcase](https://github.com/IdeaHunter/node-addon-testcase) and added minimal set of files and brief description for the case.

Nan version: 2.2.0
Node version: 5.3.0
NPM version: 3.5.2
OS: Ubuntu 15.10
gcc version: 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2) 

Any help on this issue would be appreciated

**Comment by kkoopa** [comment]
You are doing a use-after-free which leads to undefined behavior. Both your pointers are freed as soon as they are made, since you are not hanging on to the the objects owning them (the `Nan::Uf8String`s).

**Comment by IdeaHunter** [comment]
Thank you. 

So, your point is that *first argument* were freed before actual value touched the test case, and if i would copy args values to another variable created with `new` everything would be fine, and code below would be ok:

```c++
NAN_METHOD(Method) {
  const char* first = *Nan::Utf8String(info[0]);
  const char* second = *Nan::Utf8String(info[1]);
  char* result = new char[200];
  sprintf (result, "%s %s",first ,second);
  info.GetReturnValue().Set(Nan::New(result).ToLocalChecked());
}
```

**Comment by IdeaHunter** [comment]
@kkoopa i tried to change the code as above but it still give me a different result for debug and release build
For example if i would pass different first and second agrument to that function - it would return something strange for --debug build:

```javascript
test('First argument','Second argument')==='Second argument Second argument'
```

I even tried to pass params to `stderr` but with no luck - it tells me that the both args are same.

**Comment by kkoopa** [comment]
No, that has the same problem. You need to keep the Utf8String object around until you are done with the buffer it owns. Either reserve a place for it on the stack, or dereference it directly as an argument to a function that copies the buffer contents.

strcpy(result, *Utf8String(info[0]))

would work

**Comment by IdeaHunter** [comment]
@kkoopa thanks a lot for help and light-speed-like response. Initially i thought that Utf8String are just helper that would give me pointer to object that held by node string wrapper and node would not gc anything before my function done.

**Comment by kkoopa** [comment]
You are welcome. As you now know, it is in fact a class and its memory is managed to prevent memory leaks, which inevitably would happen otherwise. If I don't remember wrong, V8 internally stores string data as 16-bit strings, so it would actually be impossible to directly get a pointer to an UTF-8 string from a `v8::String`.

The [atual code](https://github.com/nodejs/nan/blob/master/nan.h#L889-L929) should clarify any further questions you may have. As can be seen, the destructor calls `free` on the allocated memory block if it was a large string which had memory heap allocated. If the string was small, the char array member of the `Utf8String` class still ceases to be valid once the object is destroyed, which happens when it goes out of scope.

As your original code used `UTF8String` as an rvalue, it was destroyed immediately after creation. When created within the arguments part of a function call, it is destroyed at the end of the called function, since that function's scope ceases to exist.
