### ISSUE TITLE
No null checks when creating new strings

### ISSUE THREAD

**Issue by mscdex** [nodejs/nan#540]
Currently nan does not check `if (value == nullptr)` before passing `value` to the v8 API, which will crash if it receives a null string. It would be nice if it did have a check and if true, it would simply return `v8::String::Empty()`.

**Comment by kkoopa** [comment]
I'll counter by claiming that it is the user's responsibility not to pass null pointers where not intended. Ideally NAN should be seamless, not doing unexpected things under the hood. If null pointers are being erroneously passed, it means that there is an error in user code. Hiding this problem is arguably worse. However, if V8 were to change the string construction API to work in this way, it would be a different matter.

**Comment by mscdex** [comment]
Digging a little deeper it seems like passing null pointers to v8 is not the actual problem (the backtrace is apparently misleading). It seems to be compiler-related. What I've learned so far: g++ (at least) 5.2.1 === bad, g++ 4.9 === good.

**Comment by bnoordhuis** [comment]
Potential culprits are the memcmp() and memcpy() compiler intrinsics, gcc optimizes those more aggressively than it used to.  Passing in NULL is UB per spec but used to work in practice when size=0.

**Comment by mscdex** [comment]
In the end it actually had to do with the C++11 ABI being enabled by default in g++ 5. My addon was compiled under 5 with the new ABI and the shared library I was binding to was compiled with the old ABI under 4.9. Recompiling the shared library (or disabling the new ABI during compile time in my addon) made things work like before.
