### ISSUE TITLE
npm published version of 2.2.1 is missing README.md

### ISSUE THREAD

**Issue by tomhughes** [nodejs/nan#554]
The npm published version of 2.2.1 is missing the README.md file.

**Comment by kkoopa** [comment]
Yeah, I noticed. It's some variant of [that ever-persistent npm bug](https://github.com/npm/npm/issues/5082). I'm tired of npm repeatedly breaking published packages. However, since it does not break functionality, I don't think it's worth the effort of publishing a new update just for a missing readme. It will eventually get fixed in some forthcoming release, presumably NAN 3.0.
