### ISSUE TITLE
how to create custom errors

### ISSUE THREAD

**Issue by mbroadst** [nodejs/nan#586]
I see you guys have provided `Nan::Error` to create proper error objects with backtraces from our addons, but I was wondering whether it was possible to further customize the name of said errors such that they could e.g. be used in bluebird's  `.catch` (`promise.catch(MySpecialError, ... `) ?

I can't see anything off the to of my head that would let me do this, other than perhaps trying to build an error object myself and using something `v8::Exception::GetStackTrace()`, etc. Maybe you guys have a better idea?

**Comment by kkoopa** [comment]
It cannot be done in any easy way. You can create a script which builds an error and returns it, run the script, then throw the returned error, but that is a lot of work.

You are better off doing this on the JavaScript side. Create a wrapper that calls your native function, have that return some error value instead of throwing, then throw in your JavaScript function based on the returned error. If you can manage with the number of native error types, you could alternatively throw one of those in your native code, intercept it in the wrapper and rethrow a custom error based on it.

**Comment by mbroadst** [comment]
@kkoopa yeah I feared as much, thank you for the quick response.
