### ISSUE TITLE
XCode 8.0 issue? clang: warning: libstdc++ is deprecated...

### ISSUE THREAD

**Issue by rwaldron** [nodejs/nan#606]
This morning I updated to XCode 8.0. Since the update, build/rebuild/install etc. of projects that use NAN are producing this message: 

```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
```

For example: 

```
$ npm install bufferutil
-
> bufferutil@1.2.1 install /Users/rwaldron/robotz/t2-precompiled-specific-abi/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
bufferutil@1.2.1 node_modules/bufferutil
├── bindings@1.2.1
└── nan@2.4.0
```

Environment details: 

- OSX 10.11.6
- Node 4.5.0: 
```
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '4.5.0',
  v8: '4.5.103.37',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2h' }
```
- Node 6.5.0
```
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '6.5.0',
  v8: '5.1.281.81',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
```

Let me know if more information is needed.

**Comment by bnoordhuis** [comment]
Native modules inherit libstdc++ from node.js.  Node v7 will link to libc++.

I'll close, not a nan issue.

**Comment by springmeyer** [comment]
FWIW you can override the std c++ library in your binding.gyp like https://github.com/mapnik/node-mapnik/blob/c8dee11e7e8f29168cf4e96c46b13d4933246327/binding.gyp#L115-L120. On OS X it works to link your addon to libc++ even against a node binary that links to libstdc++ (I assume because of work done by apple to make them binary compatible). I've been doing this without a problem (to enable the use of C++11 in addons) since node 0.10.x

**Comment by rinogo** [comment]
For those who hit this via Google: Updating to a newer version of Node seems to fix the problem for me.
