### ISSUE TITLE
What may cause memory leak?

### ISSUE THREAD

**Issue by edin-m** [nodejs/nan#613]
I have wrapped Qt's ```QRect``` class using ```nan```, however when I create it large number of times, process' memory usage increases. I am beginner at ```nan``` so I am not sure if I have done everything correctly.

My core is here: [QRectWrap.cc](https://github.com/edin-m/node-qt5/blob/master/src/QtCore/QRectWrap.cc) and the code I'm using to build up memory is:

```javascript
var qt = require...

function f(i) {
  var r = new qt.QRect(1, 2, 3, 4);
  if (i % 1000000) console.log(r.x, r.y, r.width, r.height, i);
}

var x = 99999999999;

while (x > 0) {
  f(x);
  x--;
}
```

Am I using ```nan``` correctly and is this correct way to test for memory leaks? Is it expected to have memory build up as this program runs?

**Comment by agnat** [comment]
In short, yes, that's expected. Javascript is a garbage-collected language. That is, the engine decides when to reclaim memory. So, no, this is not a good way to check for leaks.

However, for testing purposes it is possible to trigger the garbage collection manually. Just google it. Also, a bunch of cool people wrote about [node.js leak testing](http://lmgtfy.com/?q=node.js+leak+testing)...

Closing since it is not really a nan issue.
