### ISSUE TITLE
How to pass a 32bit Integer back to NodeJS?

### ISSUE THREAD

**Issue by davidgatti** [nodejs/nan#620]
From NodeJS I'm passing two integers that I want to sum in C++. Then I want to pass the result back to NodeJS. How do I send back the 32 bit integer? This is the code in C++:

```C
NAN_METHOD(Sum)
{
	unsigned int nrOne = info[0]->Uint32Value();
	unsigned int nrDwo = info[1]->Uint32Value();

	uint32_t sum = nrOne + nrDwo;

	info
	.GetReturnValue()
	.Set(
		Nan::CopyBuffer(sum, 8)
	.ToLocalChecked());
}
```

`NewBuffer()`, accepts only unsigned chars. I want to go over 255 :)

**Comment by addaleax** [comment]
You should be able to use `Nan::New<Uint32>(sum)` instead of `Nan::CopyBuffer(sum, 8)`, and get a proper JS `number` as the return value.

(I am not sure what `Nan::CopyBuffer(sum, 8)` is here for in the first place – you can use `Nan::CopyBuffer(&sum, sizeof(sum))` if you want the byte pattern for `sum` as a `Buffer`, but that seems a bit like overkill here.)

**Comment by davidgatti** [comment]
Thank you @addaleax very much it worked 🤓. About the CopyBuffer, it was a left over after some experiments :)
