### ISSUE TITLE
How to enumerate named property?

### ISSUE THREAD

**Issue by 2dxgujun** [nodejs/nan#762]
nan version: 2.10.0
node version 8.2.1

I got following error when I try to `console.log` a property.
```
TypeError: Cannot convert a Symbol value to a string
    at formatValue (util.js:330:38)
    at formatProperty (util.js:795:15)
    at util.js:643:12
    at Array.map (native)
    at formatObject (util.js:642:15)
    at formatValue (util.js:582:16)
    at Object.inspect (util.js:197:10)
    at REPLServer.self.writer (repl.js:357:19)
    at finish (repl.js:477:38)
    at REPLServer.defaultEval (repl.js:277:5)
```

```cpp
// hello.cc
#include <nan.h>

using namespace v8;
using namespace node;

NAN_PROPERTY_GETTER(Status) {
  Nan::Utf8String p(property);
  std::string PropertyName(*p);
  if (PropertyName == "Hello") {
    info.GetReturnValue().Set(Nan::New(0));
    return;
  }
  info.GetReturnValue().SetUndefined();
}

NAN_PROPERTY_ENUMERATOR(Status) {
  Local<Array> arr = Nan::New<Array>();
  Nan::Set(arr, 0, Nan::New("Hello").ToLocalChecked());
  info.GetReturnValue().Set(arr);
}

NAN_MODULE_INIT(init) {
  Local<ObjectTemplate> ObjTemplate = Nan::New<ObjectTemplate>();
  Nan::SetNamedPropertyHandler(ObjTemplate, Status, nullptr, nullptr, nullptr, Status);
  Nan::Set(target, Nan::New("Status").ToLocalChecked(), Nan::NewInstance(ObjTemplate).ToLocalChecked());
}

NODE_MODULE(hello, init);

```
```js
// index.js
var hello = require('bindings')('hello')
console.log(hello.Status)
```

**Comment by mkrufky** [comment]
Have you tried to `json.stringify` it before `console.log`ing it?

```console.log(JSON.stringify(hello.Status))```

**Comment by 2dxgujun** [comment]
Yes, thanks, it can print the string, but there is no symbol type in `hello.Status` and why I can't directly print it?

**Comment by 2dxgujun** [comment]
Hi, I modify the **nan.h** header file, and set the `flags` to `kOnlyInterceptStrings`, then it works well.

```
2524 #if NODE_MODULE_VERSION > NODE_0_12_MODULE_VERSION
2525   tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
2526       getter_, setter_, query_, deleter_, enumerator_, obj, v8::PropertyHandlerFlags
2527       ::kOnlyInterceptStrings));
```
Check [this](https://v8docs.nodesource.com/node-8.9/d2/dc3/namespacev8.html#af83cddede5015aaa9e4ce67190242080) v8 document. I get confused, here says **Will not call into interceptor for symbol lookup**.

**Comment by kkoopa** [comment]
I was not aware of that flag. Good find. I am however not sure if we can implement that same change right away or if that will break user code relying on the current behavior. Still, `Symbol`s are not supported by NAN and will not be so until the code for old V8 versions without `Symbol` support has been removed. Perhaps this could be treated as a bug fix.

Making the options configurable would probably not work nicely, since those options are not available in old versions of V8.

I do not currently have time to work out the best solution, but the recommended workaround for now would be to copy the definition of `Nan::SetNamedPropertyHandler` to some header of your own and make a new function `MySetNamedPropertyHandler` or whatever you desire to call it, include your modification and use that new function in your code. That way you can still update mainline NAN through npm without losing your patch.

**Comment by 2dxgujun** [comment]
Good idea, thanks
