### ISSUE TITLE
v8docs.nodesource.com links are broken

### ISSUE THREAD

**Issue by corystegel** [nodejs/nan#871]
All the doc links to v8docs are 404s. It seems like they got taken down for node 8.11 and only 8.16 are up now. 

For example, [Nan::DefineOwnProperty()](https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_define_own_property) has a link to https://v8docs.nodesource.com/node-8.11/db/d85/classv8_1_1_object.html#a6f76b2ed605cb8f9185b92de0033a820 which 404s.

If it is changed to https://v8docs.nodesource.com/node-8.16/db/d85/classv8_1_1_object.html#a6f76b2ed605cb8f9185b92de0033a820 then it works.

Seems similar to this: https://github.com/nodejs/nan/issues/503

**Comment by kkoopa** [comment]
Fixed in 6cc57440ccab5e6961c88b9f809fe2d2c48664bb.

For future reference, `sed -i '' 's_https://v8docs.nodesource.com/node-8.11/_https://v8docs.nodesource.com/node-8.16/_g' README.md doc/*` fixes all links (where the id hash remains unchanged), which is verifiable by `for url in $(sed -n 's_^.*(\(https://v8docs.nodesource.com/[^)]*\)).*$_\1_gp' README.md doc/*); do printf '%s ' "${url}"; wget -qSO/dev/null "${url}" 2>&1 | head -n1 | sed -n 's_^ *[^ ][^ ]* \([^ ][^ ]*\) .*$_\1_p'; done`.

**Comment by corystegel** [comment]
Awesome, thanks for the quick fix!
