### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nan#920]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

The only references I see in the repo to master (other than in links to licence files which should redirect on their own) are:

* .dntrc
* README.md

There two would required an update to change master -> main at the same time.

Opening this issue to see what the best way to get the update done.  I can rename the branch/update those two files but might better if somebody active in the project does it.

**Comment by mhdawson** [comment]
@kkoopa  do you think there is anything else that would have to go along with the rename. If not would you be ok if I went ahead and did those two changes and the branch rename?

**Comment by kkoopa** [comment]
Please go ahead, I think it will be fine. There should not be any hard dependencies on branch names. Might be something with CI integration, but that does not even work for Travis any more due to their OS credit embargo and I cannot apply for a status change there since it is tied to the Node.js org. AppVeyor should still be fine .

On October 4, 2021 6:57:52 PM GMT+03:00, Michael Dawson ***@***.***> wrote:
***@***.***  do you think there is anything else that would have to go along with the rename. If not would you be ok if I went ahead and did those two changes and the branch rename?

**Comment by mhdawson** [comment]
@kkoopa thanks, renamed.

**Comment by fivdi** [comment]
>  Might be something with CI integration, but that does not even work for Travis any more due to their OS credit embargo

It may be possible to (partially) resolve this Travis issue by using the Travis CI partner queue solution.
See https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution

This worked for me in several projects. To switch over to the partner queue solution it was only necessary to put the following in `.travis.yaml`:
```
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
```
For example, it works [here](https://github.com/fivdi/i2c-bus/blob/master/.travis.yml#L1-L5). `amd64`, which is the default `arch` is only available for commercial use. Partner queue solution builds cost 0 credits. I wouldn't expect it to work for osx though.

**Comment by kkoopa** [comment]
Thanks for the tip. I shall keep it in mind.
